import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",

    // `.next/**` above only covers the DEFAULT distDir, and this repo does not
    // use only the default distDir: next.config.ts honours NEXT_DIST_DIR, so
    // the desktop build writes `.next-desktop/`, e2e runs write
    // `.next-desktop-e2e-<pid>/`, and parallel agent runs write
    // `.next-codex-*/` — all of them gitignored generated output, and each one
    // roughly 0.1–1.8GB of minified bundle chunks.
    //
    // Without this line ESLint walks every stale build dir on the machine and
    // type-checks emitted chunks: measured 6.3GB across 11 such dirs on one
    // checkout, at which point `bun run lint` had burned 6+ minutes of CPU
    // with no result and had to be killed. Lint time must scale with the
    // amount of SOURCE, not with how many builds happen to be on disk.
    //
    // No source file loses coverage here: every one of these directories is
    // generated by `next build` and is already in .gitignore.
    ".next-*/**",
  ]),
]);

export default eslintConfig;
